Repository Normation/rudder-plugins, pull requests merged in 2018-07, with the labels that each got.

#48 Fixes #12850: Correct packaging for branding plugin
  branding/packaging/postinst
Labels: qa: Can't merge

#52 Fixes #12890: Add missing class to make Branding page UI pretty
  branding/src/main/elm/brandingManagement.html
Labels: qa: Can't merge

#53 Fixes #12894: plugin-common-compilation-error when building on 4.3.0
  plugins-common/src/main/scala/com/normation/plugins/PluginData.scala
Labels: qa: Can't merge

#57 Fixes #12910: Remove plugin-common from rudder-plugins
  Makefile
  README.md
  api-authorizations/pom-template.xml
  blank-template/pom-template.xml
  branding/pom-template.xml
  datasources/pom-template.xml
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
  helloworld/pom-template.xml
  main-build.conf
  makefiles/global-vars.mk
  node-external-reports/pom-template.xml
  plugins-common-private/pom-template.xml
  plugins-common/Makefile
  plugins-common/build.conf
  plugins-common/pom-template.xml
  plugins-common/src/main/scala/com/normation/plugins/PluginData.scala
  plugins-common/src/main/scala/com/normation/plugins/RestExtractors.scala
  pom-template.xml
Labels: qa: Can't merge

#51 Fixes #12792: Datasources postinst SQL does not use Rudder connection parameters
  datasources/packaging/postinst
Labels: qa: Can't merge

#56 Fixes #12843: UI enhancement for API ACL selection
  api-authorizations/src/main/elm/sources/api-authorizations.elm
  api-authorizations/src/main/elm/toserve/media.css
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
Labels: qa: Can't merge

#58 Fixes #12909: UI enhancement for API ACL dropdown form
  api-authorizations/src/main/elm/sources/user-api-token.elm
  api-authorizations/src/main/elm/toserve/media.css
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
Labels: qa: Can't merge

#62 Fixes #12918: Datasource plugin does not declare its APIs
  datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
Labels: qa: Can't merge

#64 Fixes #12936: Missing select all/none by categories
  api-authorizations/src/main/elm/sources/api-authorizations.elm
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
Labels: Ready for merge, qa: Can't merge

#68 Fixes #12971: A part of the login form disappears if the custom bar is not activated
  branding/src/main/elm/sources/View.elm
  branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
Labels: qa: Can't merge

#70 Fixes #13002: Move plugins docs to rudder-plugins
  .gitignore
  Makefile
  datasources/README.adoc
  datasources/README.asciidoc
  node-external-reports/README.adoc
  node-external-reports/README.asciidoc
Labels: qa: Can't merge

#71 Fixes #13006: Missing images in parent PR
  datasources/images/rudder-datasources-description.png
  node-external-reports/README.adoc
Labels: qa: Can't merge

#73 Fixes #13009: Documentation for API authorizations plugin
  api-authorizations/README.adoc
  api-authorizations/README.asciidoc
  api-authorizations/docs/api-authorizations-curl-error.png
  api-authorizations/docs/api-authorizations-curl-success.png
  api-authorizations/docs/api-authorizations-curl-user-success.png
  api-authorizations/docs/api-authorizations-new-token-acl.png
  api-authorizations/docs/api-authorizations-new-token-description.png
  api-authorizations/docs/api-authorizations-user-curl.png
  api-authorizations/docs/api-authorizations-user-event-log.png
  api-authorizations/docs/api-authorizations-user-no-token.png
  api-authorizations/docs/api-authorizations-user-with-token.png
Labels: qa: Can't merge

#81 Fixes #13054: License incorrectly interpreted in several plugins
  api-authorizations/build.conf
  api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
  branding/build.conf
  branding/src/main/assembly/plugin-with-own-dependencies.xml
  branding/src/main/scala/bootstrap/rudder/plugin/BrandingConf.scala
  branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
  branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
  node-external-reports/build.conf
  node-external-reports/pom-template.xml
  node-external-reports/src/main/scala/bootstrap/rudder/plugin/NodeExternalReportsConf.scala
  node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
Labels: qa: Can't merge

#83 Fixes #13079: Incorrect verification of plugin status for API authz
  api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala
Labels: qa: Can't merge

#85 Fixes #13087: Correction on plugins for parent status check
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
  auth-backends/build.conf
  branding/src/main/scala/bootstrap/rudder/plugin/BrandingConf.scala
  branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
  branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
  changes-validation/build.conf
  changes-validation/src/main/scala/bootstrap/rudder/plugin/ChangesValidationConf.scala
  changes-validation/src/main/scala/com/normation/plugins/changesvalidation/TopBarExtension.scala
  main-build.conf
  node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
  scale-out-relay/build.conf
  scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala
  scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/DataTypes.scala
  scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayPluginDef.scala
Labels: Ready for merge
