Repository Normation/rudder-plugins, pull requests merged in 2018-08, with the labels that each got.

#92 Fixes #13268: Move doc from manual to plugin
  changes-validation/README.adoc
  changes-validation/README.asciidoc
  changes-validation/docs/images/workflows/Conflict.png
  changes-validation/docs/images/workflows/Details.png
  changes-validation/docs/images/workflows/Diff.png
  changes-validation/docs/images/workflows/Enabling.png
  changes-validation/docs/images/workflows/History.png
  changes-validation/docs/images/workflows/Informations.png
  changes-validation/docs/images/workflows/Management.png
  changes-validation/docs/images/workflows/Notification.png
  changes-validation/docs/images/workflows/Popup.png
  changes-validation/docs/images/workflows/Rule_Update_Diff.png
  changes-validation/docs/images/workflows/States.png
  changes-validation/docs/images/workflows/Table.png
  changes-validation/docs/images/workflows/Validation.png
  changes-validation/docs/images/workflows/Warning.png
Labels: Ready for merge

#90 Fixes #13265: Generate usable docs files from plugins
  .gitignore
  Makefile
  datasources/README.adoc
  node-external-reports/README.adoc
Labels: Ready for merge, qa: Can't merge

#94 Fixes #13283: Update build so that licensed binaries don't embed key/license
  blank-template/src/main/scala-templates/limited/com/normation/plugins/BLANK/EnablePluginImpl.scala
  datasources/src/main/scala-templates/limited/com/normation/plugins/datasources/EnablePluginImpl.scala
  main-build.conf
  makefiles/common-scala-plugin.mk
  node-external-reports/src/main/scala-templates/limited/com/normation/plugins/nodeexternalreports/EnablePluginImpl.scala
  plugins-common-private/build.conf
  plugins-common-private/pom-template.xml
  plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala
Labels: qa: Can't merge
