Repository Normation/rudder-plugins, pull requests merged in 2020-11, with the labels that each got.

#343 Fixes #18470: Fix link to create-node API doc
  create-node-api/README.adoc
Labels: Ready for merge, qa: Can't merge

#345 Fixes #18519: User Plugin can not be build with previous version of Rudder API
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#349 Fixes #18630: Fix plugins build according to 6.2 changes
  branding/src/main/scala/com/normation/plugins/branding/api/BrandingApi.scala
  change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
  create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
  create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
  datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
  datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
  datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
  datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/services/GetActiveTechniqueIds.scala
  user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
Labels: qa: Can't merge

#350 Fixes #18643: Datasources test in error
  datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
  datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
  datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
Labels: Trigger test, qa: Can't merge

#351 Fixes #18697: datasource tests *still* in error
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
Labels: Ready for merge
