Repository Normation/rudder-plugins, pull requests merged in 2020-06, with the labels that each got.

#308 Fixes #17587: Adapt plugin to 6.1 rc releases, especially properties Hocon format
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
  create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
  datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
  datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
  datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
  datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
  main-build.conf
Labels: Ready for merge, qa: Can't merge

#298 Fixes #17347: update openscap technique to improve technique documentation
  openscap-policies/configuration/techniques/plugin_openscap_report.json
Labels: qa: Can't merge

#313 Fixes #17714: Typo in vault documentation
  vault/README.adoc
Labels: Ready for merge

#315 Fixes #17742: remove openscap sanitization
  openscap-policies/README.adoc
  openscap-policies/docs/images/openscap-policies/openscap-directive.png
  openscap-policies/docs/images/openscap-policies/openscap-tab.png
  openscap-policies/src/main/resources/template/OpenScapPoliciesManagement.html
  openscap-policies/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
  openscap-policies/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
Labels: Ready for merge

#321 Fixes #17864: rename to openscap
  openscap-policies/src/main/resources/openscap-policies.properties
  openscap/LICENSE
  openscap/LICENSE_EXCEPTION
  openscap/Makefile
  openscap/README.adoc
  openscap/README.asciidoc
  openscap/build.conf
  openscap/configuration/techniques/plugin_openscap_report.json
  openscap/docs/images/openscap/openscap-directive.png
  openscap/docs/images/openscap/openscap-tab.png
  openscap/packaging/metadata
  openscap/packaging/postinst
  openscap/packaging/prerm
  openscap/packaging/remove_configuration
  openscap/pom-template.xml
  openscap/src/main/resources/antisamy.xml
  openscap/src/main/resources/antisamy.xsd
  openscap/src/main/resources/openscap.properties
  openscap/src/main/resources/template/OpenScapPoliciesManagement.html
  openscap/src/main/resources/toserve/openscappolicies/openscap-policies.css
  openscap/src/main/resources/toserve/openscappolicies/openscap-policies.js
  openscap/src/main/scala-templates/default/com/normation/plugins/openscappolicies/EnablePluginImpl.scala
  openscap/src/main/scala-templates/limited/com/normation/plugins/openscappolicies/EnablePluginImpl.scala
  openscap/src/main/scala/bootstrap/rudder/plugin/OpenscapPoliciesConf.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/DataTypes.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/OpenscapPoliciesPluginDef.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/services/GetActiveTechniqueIds.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/services/OpenScapReportReader.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/services/ReportSanitizer.scala
  openscap/src/node-external-reports.properties
  openscap/src/test/resources/logback-test.xml
  openscap/src/test/scala/com/normation/plugins/openscappolicies/placeholder
  openscap/tools/openscap
Labels: Ready for merge

#324 Fixes #17871: Add screenshot in Branding
  branding/README.adoc
  branding/doc/images/branding_conf.png
Labels: Ready for merge
