Repository Normation/rudder-plugins, pull requests merged in 2021-09, with the labels that each got.

#409 Fixes #17733: Security/Monitoring report from external node reports appears on "System status" tab
  node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
Labels: Ready for merge, Trigger test

#412 Fixes #19917: Missing implementation of method in test
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
Labels: Ready for merge, Trigger test

#410 Fixes #19905: Evolve plugin build to support a separate branching scheme in 7.0.0
  Makefile
  main-build.conf
  makefiles/common-scala-plugin.mk
  makefiles/common.mk
  makefiles/global-vars.mk
  makefiles/make-plugins-common.mk
Labels: Ready for merge

#413 Fixes #19928: Remove warning about unit expression
  scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
Labels: Ready for merge

#411 Fixes #19909: Bad use of toString in place of serialize in change-validation
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
Labels: Trigger test

#414 Fixes #19958: stack trace when openscap plugin loads
  openscap/pom-template.xml
Labels: qa: Can't merge, Trigger test
