Repository Normation/rudder-plugins, pull requests merged in 2021-05, with the labels that each got.

#368 Fixes #19230: Add dependency check for plugins
  Jenkinsfile-security
  dependency-check-suppression.xml
Labels: Trigger test, qa: Can't merge

#372 Fixes #19253: Set vulnerability level to a higher value
  Jenkinsfile-security
Labels: Trigger test, qa: Can't merge

#373 Fixes #19256: build plgin commons before checking dependencies
  Jenkinsfile-security
Labels: qa: Can't merge

#374 Fixes #19275: Ignore security alert for unused js embeded in scala lib (plugin)
  dependency-check-suppression.xml
Labels: Trigger test

#375 Fixes #19279: For plugins, we need to skip CVE check on provided dependencies
  Jenkinsfile-security
Labels: Trigger test

#364 Fixes #19147: Email notification should be disabled when no host server is configured
  change-validation/README.adoc
  change-validation/src/main/resources/template/ChangeValidationManagement.html
  change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala
Labels: Trigger test

#358 Fixes #18979: Add licenses tag in plugins pom
  main-build.conf
  pom-template.xml
Labels: Trigger test, qa: Can't merge

#376 Fixes #19252:
  openscap/pom-template.xml
  openscap/src/main/resources/antisamy.xml
  openscap/src/main/resources/antisamy.xsd
Labels: Ready for merge, Trigger test
