Repository Normation/rudder-plugins, pull requests merged in 2021-04, with the labels that each got.

#361 Fixes #19148: Parsing error when the port is undefined in change-validation.conf
  change-validation/src/main/resources/change-validation.conf
Labels: Ready for merge, Trigger test

#362 Fixes #19165:
  api-authorizations/pom-template.xml
  auth-backends/pom-template.xml
  branding/pom-template.xml
  change-validation/pom-template.xml
  create-node-api/pom-template.xml
  datasources/pom-template.xml
  helloworld/pom-template.xml
  node-external-reports/pom-template.xml
  openscap/pom-template.xml
  plugins-common-private/pom-template.xml
  pom-template.xml
  scale-out-relay/pom-template.xml
  user-management/pom-template.xml
Labels: Ready for merge, Trigger test, qa: Can't merge

#363 Fixes #19168:
  src/main/g8/pom-template.xml
Labels: Trigger test

#365 Fixes #19182: Change validation details page is not accessible anymore when a Node group query has been modified
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
  main-build.conf
Labels: qa: Can't merge
