Repository Normation/rudder-plugins, pull requests merged in 2022-06, with the labels that each got.

#476 Fixes #21198: Dockerize dependency-check
  Jenkinsfile-security
  ci/dep-check.Dockerfile
Labels: Trigger test

#477 Fixes #21208: Missing make dependancy
  ci/dep-check.Dockerfile
Labels: Ready for merge

#478 Fixes #21209: Dependency check fails
  Jenkinsfile-security
Labels: qa: Can't merge, Ready for merge

#475 Fixes #21193: Add PR tests for webapp plugins
  Jenkinsfile
  Makefile
  ci/plugins.Dockerfile
  makefiles/global-vars.mk
Labels: qa: Can't merge, Trigger test

#480 Fixes #21217: Broken build of maven plugins with elm apps after minification
  api-authorizations/src/main/elm/build.sh
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
  auth-backends/src/main/elm/build.sh
  branding/src/main/elm/build.sh
  change-validation/src/main/elm/build.sh
  user-management/src/main/elm/build.sh
Labels: Ready for merge

#481 Fixes #21228: Bad warning about missing config for oauth when oauth backend is not used
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
Labels: Trigger test

#483 Fixes #21250: Add case-sentitivity parameter in user file example
  auth-backends/README.adoc
  user-management/README.adoc
Labels: Trigger test
