Repository Normation/rudder-plugins, pull requests merged in 2022-05, with the labels that each got.

#468 Fixes #21029: Improve integration of the Change Validation plugin in the 7.0 interface
  change-validation/src/main/elm/sources/View.elm
  change-validation/src/main/resources/template/ChangeValidationManagement.html
  change-validation/src/main/resources/template/changeRequest.html
  change-validation/src/main/resources/template/changeRequests.html
  change-validation/src/main/resources/toserve/changevalidation/ComponentChangeRequest.html
  change-validation/src/main/resources/toserve/changevalidation/change-validation.css
  change-validation/src/main/resources/toserve/changevalidation/change-validation.js
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
Labels: Trigger test

#469 Fixes #21037: Remove create-node-api menu entry and page
  create-node-api/build.conf
  create-node-api/src/main/resources/template/CreateNodeApiManagement.html
  create-node-api/src/main/resources/toserve/createnodeapi/create-node-api.css
  create-node-api/src/main/resources/toserve/createnodeapi/create-node-api.js
  create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApiPluginDef.scala
Labels: qa: Can't merge, Trigger test

#465 Fixes #21015: documentation dones't tell which provider to user of oauth2
  auth-backends/README.adoc
  auth-backends/docs/images/oauth2-oidc-login-form.png
Labels: qa: Can't merge, Trigger test

#470 Fixes #21076: Backport 21021 because same NPE happens in 6.2
  auth-backends/pom-template.xml
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
Labels: qa: Can't merge, Trigger test

#471 Fixes #21114: Hello world plugin does not compile anymore
  helloworld/src/main/scala/bootstrap/rudder/plugin/HelloWorldConf.scala
Labels: Ready for merge, Trigger test

#473 Fixes #21136: Minify js produced by elm - plugins
  api-authorizations/src/main/elm/build-app.sh
  api-authorizations/src/main/elm/build.sh
  api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
  auth-backends/src/main/elm/build-app.sh
  auth-backends/src/main/elm/build.sh
  auth-backends/src/main/resources/template/AuthBackendsManagement.html
  branding/src/main/elm/build-app.sh
  branding/src/main/elm/build-dev.sh
  branding/src/main/elm/build.sh
  branding/src/main/resources/template/brandingManagement.html
  change-validation/src/main/elm/build-app.sh
  change-validation/src/main/elm/build-dev.sh
  change-validation/src/main/elm/build.sh
  change-validation/src/main/resources/template/ChangeValidationManagement.html
  plugins-common/elm.sh
  plugins-common/pom-template.xml
  user-management/src/main/elm/build-app.sh
  user-management/src/main/elm/build-dev.sh
  user-management/src/main/elm/build.sh
  user-management/src/main/resources/template/UserManagement.html
Labels: qa: Can't merge, Ready for merge, Trigger test
