Repository Normation/rudder-plugins, pull requests merged in 2022-04, with the labels that each got.

#459 Fixes #20967: Notifyd doesn't work with python3
  notify/packaging/metadata
  notify/packaging/postinst
  notify/share/python/log_tail.py
  notify/share/python/notify.py
  notify/share/python/notifyd.py
Labels: Ready for merge, Trigger test

#451 Fixes #20778: Add Oauth2/openid connect backend
  auth-backends/README.adoc
  auth-backends/pom-template.xml
  auth-backends/src/main/resources/applicationContext-security-auth-oauth2.xml
  auth-backends/src/main/resources/applicationContext-security-auth-oidc.xml
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala
Labels: Trigger test

#461 Fixes #20997: Incorrect error of missing oauth config when the backend is disabled
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
Labels: qa: Can't merge, Trigger test

#458 Fixes #20962: Change the default background colour of the bar to make it more visible
  branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala
Labels: Trigger test

#457 Fixes #20859: Prevent acl categories to fold when we click on the All or None buttons
  api-authorizations/src/main/elm/sources/ApiAuthorizations.elm
  api-authorizations/src/main/resources/toserve/apiauthorizations/media.css
Labels: Trigger test

#460 Fixes #20992: Improve the integration of the plugin in the 7.0 interface
  datasources/src/main/resources/template/dataSourceManagement.html
  datasources/src/main/resources/toserve/datasources/rudder-datasources.css
  datasources/src/main/resources/toserve/datasources/rudder-datasources.js
Labels: Trigger test

#462 Fixes #21006: Plugin can not be installed in 7.0.2
  openscap/packaging/postinst
Labels: Trigger test

#463 Fixes #21008: Plugins package scripts should always exit on error
  Jenkinsfile
  ansible-policies/packaging/postinst
  ansible-policies/packaging/prerm
  api-authorizations/packaging/postinst
  auth-backends/packaging/postinst
  branding/packaging/postinst
  change-validation/packaging/postinst
  cis/packaging/postinst
  cis/packaging/prerm
  create-node-api/packaging/postinst
  datasources/packaging/postinst
  glpi/packaging/postinst
  helloworld/packaging/postinst
  node-external-reports/packaging/postinst
  notify/packaging/postinst
  openscap/packaging/postinst
  openscap/packaging/prerm
  qa-test
  scale-out-relay/packaging/postinst
  user-management/packaging/postinst
  zabbix/packaging/postinst
Labels: qa: Can't merge, Trigger test

#464 Fixes #21017: Login form is not update in 7.0
  auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala
Labels: Trigger test

#467 Fixes #21024: Oauth login error are not logged nor displayed on rudder login screen
  auth-backends/pom-template.xml
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
Labels: Trigger test
