Repository Normation/rudder-plugins, pull requests merged in 2022-08, with the labels that each got.

#490 Fixes #21514: Correct tests in datasources
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
Labels: qa: Can't merge

#486 Fixes #21428: output of install of scale out relay is clearly not great
  scale-out-relay/packaging/postinst
Labels: qa: Can't merge, Trigger test

#489 Fixes #21509: Adapt datasource to new test config-repo
  datasources/src/test/resources/configuration-repository/techniques/applications/category.xml
  datasources/src/test/resources/configuration-repository/techniques/applications/packageManagement/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/applications/rpmPackageInstallation/7.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/category.xml
  datasources/src/test/resources/configuration-repository/techniques/fileDistribution/category.xml
  datasources/src/test/resources/configuration-repository/techniques/fileDistribution/copyGitFile/2.3/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/fileDistribution/fileTemplate/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/ncf_techniques/Create_file/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/ncf_techniques/category.xml
  datasources/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/system/category.xml
  datasources/src/test/resources/configuration-repository/techniques/system/common/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/system/inventory/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/system/server-roles/1.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/systemSettings/category.xml
  datasources/src/test/resources/configuration-repository/techniques/systemSettings/misc/category.xml
  datasources/src/test/resources/configuration-repository/techniques/systemSettings/misc/clockConfiguration/3.0/metadata.xml
  datasources/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/2.0/metadata.xml
Labels: qa: Can't merge, Ready for merge

#488 Fixes #21493: Update bouncycastle for 7.2 - plugins
  plugins-common/pom-template.xml
Labels: qa: Can't merge, Ready for merge

#491 Fixes #21540: Force mvn update for building plugins
  Jenkinsfile
Labels: qa: Can't merge, Ready for merge

#492 Fixes #21543: Pass --update to all maven commands
  Jenkinsfile
Labels: qa: Can't merge
