Repository Normation/rudder-plugins, pull requests merged in 2022-01, with the labels that each got.

#433 Fixes #20514: Copy main-build.conf into plugin jar
  plugins-common/pom-template.xml
Labels: Trigger test

#434 Fixes #20527: Allow to have non verified connection to centreon server, and improve documentation
  centreon/README.adoc
  centreon/bin/centreon-plugin
  centreon/packaging/postinst
  centreon/share/python/centreonapi/centreon.py
  centreon/share/python/centreonapi/webservice/__init__.py
Labels: Ready for merge, Trigger test

#428 Fixes #19703: openscap display is broken in 7.0
  openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
Labels: Trigger test

#432 Fixes #20447:
  openscap/pom-template.xml
Labels: qa: Can't merge, Ready for merge, Trigger test

#436 Fixes #20575: Port technique to 7.0 techniques API
  ansible-policies/configuration/techniques/ansible_policies.json
  ansible-policies/packaging/postinst
  openscap/packaging/postinst
Labels: Trigger test

#435 Fixes #20574: Fix plugin branding after plugin version changes
  branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
  branding/src/main/scala/com/normation/rudder/rest/BrandingApiSchema.scala
Labels: qa: Can't merge

#437 Fixes #20594: Update the Branding plugin following changes to the Login page
  branding/src/main/elm/sources/View.elm
  branding/src/main/resources/toserve/branding/media.css
  branding/src/main/scala/com/normation/plugins/branding/BrandingConf.scala
  branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
  branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
Labels: qa: Can't merge, Trigger test

#438 Fixes #20613: Document ldaps needs certificate added in jvm keystore
  auth-backends/README.adoc
Labels: Ready for merge, Trigger test

#440 Fixes #20620: In 7.0 the plugin does not install any directives nor techniques
  cis/src/debian9/techniques/Disable_Service.json
  cis/src/debian9/techniques/Disable_kernel_module_loading.json
  cis/src/debian9/techniques/Enable_Service.json
  cis/src/debian9/techniques/Ensure_a_package_is_installed.json
  cis/src/debian9/techniques/Ensure_a_package_is_not_installed.json
  cis/src/debian9/techniques/Ensure_gpgcheck_is_globally_activated.json
  cis/src/debian9/techniques/Ensure_key_value_in_file.json
  cis/src/debian9/techniques/Ensure_lines_present_in_file.json
  cis/src/debian9/techniques/Ensure_mounting_partition_is_correct.json
  cis/src/debian9/techniques/Ensure_sysctl_key_value_IPV4.json
  cis/src/debian9/techniques/Ensure_sysctl_key_value_IPV6.json
  cis/src/debian9/techniques/Execute_command.json
  cis/src/debian9/techniques/Set_permissions.json
  cis/src/redhat7/techniques/Disable_Service.json
  cis/src/redhat7/techniques/Disable_kernel_module_loading.json
  cis/src/redhat7/techniques/Enable_Service.json
  cis/src/redhat7/techniques/Ensure_a_package_is_installed.json
  cis/src/redhat7/techniques/Ensure_a_package_is_not_installed.json
  cis/src/redhat7/techniques/Ensure_gpgcheck_is_globally_activated.json
  cis/src/redhat7/techniques/Ensure_key_value_in_file.json
  cis/src/redhat7/techniques/Ensure_lines_present_in_file.json
  cis/src/redhat7/techniques/Ensure_mounting_partition_is_correct.json
  cis/src/redhat7/techniques/Ensure_sysctl_key_value_IPV4.json
  cis/src/redhat7/techniques/Ensure_sysctl_key_value_IPV6.json
  cis/src/redhat7/techniques/Execute_command.json
  cis/src/redhat7/techniques/Set_permissions.json
  cis/src/ubuntu18/techniques/Disable_Service.json
  cis/src/ubuntu18/techniques/Disable_kernel_module_loading.json
  cis/src/ubuntu18/techniques/Enable_Service.json
  cis/src/ubuntu18/techniques/Ensure_a_package_is_installed.json
  cis/src/ubuntu18/techniques/Ensure_a_package_is_not_installed.json
  cis/src/ubuntu18/techniques/Ensure_gpgcheck_is_globally_activated.json
  cis/src/ubuntu18/techniques/Ensure_key_value_in_file.json
  cis/src/ubuntu18/techniques/Ensure_lines_present_in_file.json
  cis/src/ubuntu18/techniques/Ensure_mounting_partition_is_correct.json
  cis/src/ubuntu18/techniques/Ensure_sysctl_key_value_IPV4.json
  cis/src/ubuntu18/techniques/Ensure_sysctl_key_value_IPV6.json
  cis/src/ubuntu18/techniques/Execute_command.json
  cis/src/ubuntu18/techniques/Set_permissions.json
Labels: Ready for merge, Trigger test

#441 Fixes #20650: GM should be reloaded before importing techniques
  cis/Makefile.plugin
  cis/packaging/postinst
Labels: Ready for merge, Trigger test
