Repository Normation/rudder-plugins, pull requests merged in 2022-10, with the labels that each got.

#503 Fixes #21896: Remaingin OAUTH secret in log in trace level
  auth-backends/README.adoc
  auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
Labels: qa: Can't merge

#504 Fixes #21897: OIDC doc contains a merge diff resolution comment
  auth-backends/README.adoc
Labels: Ready for merge

#505 Fixes #21907: Ignore reported batik-css CVE
  dependency-check-suppression.xml
Labels: Ready for merge

#506 Fixes #21908: Ignore reported batik-util CVE
  dependency-check-suppression.xml
Labels: Ready for merge

#509 Fixes #21927: Jackson-databind used in oauth has CVE
  auth-backends/pom-template.xml
Labels: qa: Can't merge, Ready for merge

#501 Fixes #21826: Port plugins to ZIO2
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
  branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala
  branding/src/main/scala/com/normation/plugins/branding/BrandingPluginDef.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
  datasources/pom-template.xml
  datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
  datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
  datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
  datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
  datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
  datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
  datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
  datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
  main-build.conf
  node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/NodeExternalReportPluginDef.scala
  openscap/src/main/scala/com/normation/plugins/openscappolicies/services/ReportSanitizer.scala
  plugins-common/pom-template.xml
  scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
  user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementPluginDef.scala
Labels: Ready for merge

#510 Fixes #21987: Document oauth2 common error case
  auth-backends/README.adoc
Labels: qa: Can't merge, Ready for merge

#511 Fixes #21992: New CVE in Jackson-Databind 2.13.4
  auth-backends/pom-template.xml
Labels: Ready for merge

#516 Fixes #22004: Spotless must not be exec in plugin parent
  plugins-common/pom-template.xml
Labels: qa: Can't merge, Ready for merge

#517 Fixes #22008: Spotless must not be exec in plugins-common but on children
  plugins-common/pom-template.xml
Labels: qa: Can't merge, Ready for merge
