Repository Normation/rudder-plugins, pull requests merged in 2023-03, with the labels that each got.

#538 Fixes #22364: Adapt warning message to warn about merge with divergence
  change-validation/src/main/resources/toserve/changevalidation/ComponentChangeRequest.html
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
Labels: qa: Can't merge

#540 Fixes #22441: secrets are leaking at the install of the plugin
  ansible-policies/packaging/postinst
  ansible-policies/packaging/prerm
  api-authorizations/packaging/postinst
  auth-backends/packaging/postinst
  branding/packaging/postinst
  change-validation/packaging/postinst
  cis/packaging/postinst
  cis/packaging/prerm
  create-node-api/packaging/postinst
  datasources/packaging/postinst
  glpi/packaging/postinst
  helloworld/packaging/postinst
  node-external-reports/packaging/postinst
  notify/packaging/postinst
  openscap/packaging/postinst
  openscap/packaging/prerm
  qa-test
  scale-out-relay/packaging/postinst
  user-management/packaging/postinst
  zabbix/packaging/postinst
Labels: qa: Can't merge

#541 Fixes #22455: Documentation of plugin version compatibility is outdated
  README.adoc
  version-compat.adoc
Labels: qa: Can't merge, Ready for merge

#544 Fixes #22488: Remove outdated docs
  scale-out-relay/README.adoc
Labels: qa: Can't merge, Ready for merge

#549 Fixes #22533: Upgrade nimbus-jose-jwt to last patch release
  auth-backends/pom-template.xml
Labels: Ready for merge
