Repository Normation/rudder-plugins, pull requests merged in 2024-01, with the labels that each got.

#624 Fixes #23984: Change sequence/traverse in plugins too
  change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
  datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
Labels: qa: Can't merge, Ready for merge

#625 Fixes #23986: Remove warning about missing ()
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
Labels: Ready for merge

#622 Fixes #23907: List change requests with additional filters
  change-validation/src/main/scala/bootstrap/rudder/plugin/MigrateSupervisedGroups.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/UnsupervisedTargetsReposiory.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
Labels: qa: Can't merge

#603 Fixes #23444: Impact of adding UserInfo base on public plugins
  auth-backends/README.adoc
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala
  auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
  user-management/src/main/scala/bootstrap/rudder/plugin/UserManagementConf.scala
  user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
  user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
Labels: qa: Can't merge, Ready for merge

#626 Fixes #23991: Missing some CurrentUser changes
  change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestEditForm.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
  change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepositoryTest.scala
Labels: qa: Can't merge

#627 Fixes #23994: Some more missing change for user
  api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala
  user-management/src/main/scala/bootstrap/rudder/plugin/UserManagementConf.scala
  user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
Labels: Ready for merge

#631 Fixes #24004: Add neko-htmlUnit as dependency due to security checks
  openscap/pom-template.xml
Labels: qa: Can't merge

#633 Fixes #24037: Invalid makefile because prerm was removed
  openscap/Makefile
Labels: Ready for merge

#640 Fixes #24108: Merge conflict error
  datasources/src/main/resources/template/dataSourceManagement.html
Labels: qa: Can't merge, Ready for merge

#641 Fixes #24111: Pending deployment action are completely messed up
  change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
Labels: qa: Can't merge, Ready for merge
