Repository Normation/rudder-plugins, pull requests merged in 2024-08, with the labels that each got.

#743 Fixes #25280: Clarify that we do not support authorizations in OIDC authentification role in documentation
  auth-backends/README.adoc
Labels: Ready for merge

#744 Fixes #25313: Reload users file when user is disabled or activated in plugin
  user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
  user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
Labels: qa: Can't merge, Ready for merge

#745 Fixes #25343: Setting existing users with case sensitivity in user management tests
  user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
Labels: qa: Can't merge

#746 Fixes #25378: Update to jetty 11 spring 6 on plugins
  api-authorizations/pom-template.xml
  auth-backends/pom-template.xml
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
  branding/pom-template.xml
  change-validation/pom-template.xml
  datasources/pom-template.xml
  openscap/pom-template.xml
  plugins-common/pom-template.xml
  scale-out-relay/pom-template.xml
Labels: Ready for merge

#747 Fixes #25392: Typo in pom-template
  plugins-common/pom-template.xml
Labels: Ready for merge
