Repository Normation/rudder-plugins, pull requests merged in 2024-02, with the labels that each got.

#647 Fixes #24154: The UI is barely functional
  datasources/src/main/elm/sources/APICalls.elm
  datasources/src/main/elm/sources/DataSourceForm.elm
  datasources/src/main/elm/sources/JsonDecoder.elm
  datasources/src/main/elm/sources/Messages.elm
  datasources/src/main/elm/sources/Port.elm
  datasources/src/main/elm/sources/Update.elm
  datasources/src/main/elm/sources/View.elm
  datasources/src/main/resources/template/dataSourceManagement.html
Labels: qa: Can't merge

#648 Fixes #24161: Missing write check on delete button
  datasources/src/main/elm/sources/View.elm
Labels: qa: Can't merge

#649 Fixes #24163: gulp-sass missing for datasources
  datasources/src/main/package-lock.json
  datasources/src/main/package.json
Labels: Ready for merge

#650 Fixes #24167: Actually other gulp plugins are missing
  datasources/src/main/package-lock.json
  datasources/src/main/package.json
  datasources/src/main/style/rudder-datasources.css
Labels: Ready for merge

#653 Fixes #24185: Group repository in tests should get by ids
  change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala
Labels: qa: Can't merge

#656 Fixes #24191: Make version of backport branch ok for rudder-package
  main-build.conf
  makefiles/global-vars.mk
Labels: qa: Can't merge, Ready for merge

#662 Fixes #24214: Fix UI issues caused by bootstrap update in api-authorization plugin
  api-authorizations/src/main/elm/sources/ApiAuthorizations.elm
  api-authorizations/src/main/style/media.css
Labels: qa: Can't merge

#658 Fixes #24202: No API right with OIDC provided roles
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
Labels: qa: Can't merge

#663 Fixes #24221: Fix UI issues caused by bootstrap update in datasources plugin
  datasources/src/main/elm/sources/DataSourceForm.elm
  datasources/src/main/elm/sources/Update.elm
  datasources/src/main/elm/sources/View.elm
  datasources/src/main/resources/template/dataSourceManagement.html
  datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
  datasources/src/main/style/rudder-datasources.css
Labels: qa: Can't merge

#665 Fixes #24119: GLPI plugin fails to send inventory
  glpi/bin/glpi-plugin
Labels: qa: Can't merge

#659 Fixes #24206: We need an option to force validation of change requests
  change-validation/src/main/resources/template/ChangeValidationManagement.html
  change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
  change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
Labels: qa: Can't merge, Ready for merge

#670 Fixes #24249: Fix typo in HTML of the setting to validate all changes
  change-validation/src/main/resources/template/ChangeValidationManagement.html
Labels: qa: Can't merge

#667 Fixes #24247: Authentication protocol names should be normalized to lowercase
  auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
Labels: qa: Can't merge

#666 Fixes #22731: Rudder-plugin-glpi sends inventory of node that no longer exists
  glpi/etc/hooks.d/node-post-deletion/20-clean-inventories
Labels: qa: Can't merge

#674 Fixes #24293: change validation plugin documentation refers to Rudder 5.0
  change-validation/README.adoc
Labels: qa: Can't merge
